import { F } from "https://deno.land/x/embedder@v1.0.1/embed.ts";
export default F({
  size: 333,
  encoded: `
aW1wb3J0ICogYXMgZW1iZWRkZXIgZnJvbSAiaHR0cHM6Ly9kZW5vLmxhbmQveC9lbWJlZGRlckB2MS4wLjEvbW9kLnRzIjsKCmNvbnN0IGVtYmVkZGVyT3B0
aW9uczogZW1iZWRkZXIuRGV2T3B0aW9ucyA9IHsKICBpbXBvcnRNZXRhOiBpbXBvcnQubWV0YSwKICBtYXBwaW5nczogWwogICAgeyBzb3VyY2VEaXI6ICIu
LyIsIGRlc3REaXI6ICIuLi9lbWJlZGRlcl9zdGF0aWMiIH0sCiAgXSwKfTsKCmlmIChpbXBvcnQubWV0YS5tYWluKSB7CiAgYXdhaXQgZW1iZWRkZXIubWFp
bih7CiAgICBvcHRpb25zOiBlbWJlZGRlck9wdGlvbnMsCiAgICBhcmdzOiBbImJ1aWxkIl0sCiAgfSk7Cn0K`,
});
