name: deno test
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - .github/**
      - "!.github/workflows/deno-test.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - .github/**
      - "!.github/workflows/deno-test.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deno-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno test -A
